version: "3.9"

services:
    postgres:
      image: postgres:16
      container_name: auth-service-in6bm
      restart: always
      environment:
        POSTGRES_DB: KinalSports
        POSTGRES_USER: ecujcuj
        POSTGRES_PASSWORD: admin
      ports:
       - "5435:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

    mongodb:
      image: mongo:latest
      container_name: mongodb-server-admin
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - mongodb_data:/data/db

volumes:
  postgres_data:
  mongodb_data: